### ISSUE TITLE
Support for Comments

### ISSUE THREAD

**Issue by njh** [pachet/heket#3]
Thanks for writing heket, it has been a really useful tool for writing test cases for a ABNF.

RFC5234 allows for comments by using a semicolon:

> A semicolon starts a comment that continues to the end of line.  This
> is a simple way of including useful notes in parallel with the specifications.

I tried doing this with heket but it gave a parse error.

Example code:
```js
const Heket = require('heket');

const parser = Heket.createParser(`
    foo        = *(baz / bar) wat
    ; This is Baz
    baz        = nested-baz
    nested-baz = "xxx"
    bar        = "yyy"
    wat        = [*"z"]
`);

const result = parser.parse('xxxyyyzz');
console.log(result);
```

Result:
```
node_modules/heket/index.js:96
		throw new Error(
		^

Error: Invalid value passed to createParser(): 
    foo        = *(baz / bar) wat
    ; This is Baz
    baz        = nested-baz
    nested-baz = "xxx"
    bar        = "yyy"
    wat        = [*"z"]

    at Object.createParser (node_modules/heket/index.js:96:9)
    at Object.<anonymous> (test2.js:3:22)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
```

Is this a bug or a missing feature?

Thanks,

nick.

**Comment by pachet** [comment]
Hello! Sorry for the monstrously belated response. This is due to a line-parsing bug; it should be fixed with https://github.com/pachet/heket/commit/7ff69162bf758179c36ac032f638c7ed58341503
